# Generated by Django 2.0.5 on 2018-08-08 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ('-year',),
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(default='Computer Science and Engineering', max_length=25)),
                ('branch_code', models.CharField(default='CSE', max_length=3)),
            ],
            options={
                'ordering': ('branch_name',),
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=45)),
                ('course_code', models.CharField(max_length=7)),
                ('branch', models.ManyToManyField(to='student.Branch')),
            ],
            options={
                'ordering': ('course_code',),
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_value', models.CharField(max_length=2)),
                ('course', models.ManyToManyField(to='student.Course')),
            ],
            options={
                'ordering': ('grade_value',),
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_name', models.CharField(default='Semester - 1', max_length=10)),
                ('semester_code', models.CharField(default='S1', max_length=2)),
                ('status', models.CharField(choices=[('current', 'Current'), ('past', 'Past')], default='current', max_length=10)),
            ],
            options={
                'ordering': ('semester_code',),
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('roll_no', models.PositiveIntegerField()),
                ('batch', models.ManyToManyField(to='student.Batch')),
                ('branch', models.ManyToManyField(to='student.Branch')),
                ('course', models.ManyToManyField(to='student.Course')),
                ('grade', models.ManyToManyField(to='student.Grade')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.ManyToManyField(to='student.Semester'),
        ),
    ]
