# Generated by Django 2.0.5 on 2018-08-08 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='semester',
            field=models.ManyToManyField(to='student.Semester'),
        ),
    ]
