# Generated by Django 2.0.5 on 2018-08-08 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_semester'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batch',
            options={'ordering': ('year',)},
        ),
        migrations.AlterField(
            model_name='batch',
            name='year',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='branch_code',
            field=models.CharField(blank=True, default='CSE', max_length=3),
        ),
        migrations.AlterField(
            model_name='branch',
            name='branch_name',
            field=models.CharField(blank=True, default='Computer Science and Engineering', max_length=25),
        ),
        migrations.AlterField(
            model_name='semester',
            name='semester_code',
            field=models.CharField(blank=True, default='S1', max_length=2),
        ),
        migrations.AlterField(
            model_name='semester',
            name='semester_name',
            field=models.CharField(blank=True, default='Semester - 1', max_length=10),
        ),
        migrations.AlterField(
            model_name='semester',
            name='status',
            field=models.CharField(blank=True, choices=[('current', 'Current'), ('past', 'Past')], default='current', max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='batch',
            field=models.ManyToManyField(blank=True, to='student.Batch'),
        ),
        migrations.AlterField(
            model_name='student',
            name='branch',
            field=models.ManyToManyField(blank=True, to='student.Branch'),
        ),
        migrations.AlterField(
            model_name='student',
            name='semester',
            field=models.ManyToManyField(blank=True, to='student.Semester'),
        ),
    ]
