# Generated by Django 2.0.5 on 2018-08-10 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20180808_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='branch',
            field=models.ManyToManyField(to='student.Branch'),
        ),
        migrations.AlterField(
            model_name='student',
            name='batch',
            field=models.ManyToManyField(to='student.Batch'),
        ),
        migrations.AlterField(
            model_name='student',
            name='branch',
            field=models.ManyToManyField(to='student.Branch'),
        ),
        migrations.AlterField(
            model_name='student',
            name='semester',
            field=models.ManyToManyField(to='student.Semester'),
        ),
    ]
