# Generated by Django 2.0.5 on 2018-08-10 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20180810_0252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='batch',
            field=models.ManyToManyField(blank=True, to='student.Batch'),
        ),
        migrations.AlterField(
            model_name='student',
            name='branch',
            field=models.ManyToManyField(blank=True, to='student.Branch'),
        ),
        migrations.AlterField(
            model_name='student',
            name='semester',
            field=models.ManyToManyField(blank=True, to='student.Semester'),
        ),
    ]
