# Generated by Django 2.0.5 on 2018-08-10 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_auto_20180810_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='attendace',
            field=models.PositiveIntegerField(blank=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='internel',
            field=models.PositiveIntegerField(blank=True, default=None),
            preserve_default=False,
        ),
    ]
