# Generated by Django 2.0.5 on 2018-08-10 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_auto_20180810_1844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='attendace',
        ),
        migrations.RemoveField(
            model_name='course',
            name='internel',
        ),
    ]
