# Generated by Django 2.0.5 on 2018-08-10 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_auto_20180810_1901'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=45)),
                ('course_code', models.CharField(max_length=7)),
                ('grade', models.CharField(choices=[('O', 'O'), ('A+', 'A+'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('C+', 'C+'), ('C', 'C'), ('P', 'P'), ('F', 'F'), ('FE', 'FE'), ('', '')], default='', max_length=2)),
                ('attendance', models.PositiveIntegerField(blank=True)),
                ('internal', models.PositiveIntegerField(blank=True)),
                ('branch', models.ManyToManyField(to='student.Branch')),
                ('semester', models.ManyToManyField(to='student.Semester')),
            ],
        ),
    ]
