# Generated by Django 2.0.5 on 2018-08-10 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_course'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ('course_code',)},
        ),
    ]
