# Generated by Django 2.0.5 on 2018-08-10 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_auto_20180810_1907'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('roll_no', models.PositiveIntegerField()),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Batch')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Branch')),
                ('course', models.ManyToManyField(to='student.Course')),
                ('semester', models.ManyToManyField(to='student.Semester')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
