# Generated by Django 2.0.5 on 2018-08-10 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0018_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='student',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='student',
            name='course',
        ),
        migrations.RemoveField(
            model_name='student',
            name='current_semester',
        ),
        migrations.RemoveField(
            model_name='student',
            name='past_semester',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
