# Generated by Django 2.0.5 on 2018-08-10 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0020_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='batch',
            field=models.ForeignKey(default=2015, on_delete=django.db.models.deletion.CASCADE, to='student.Batch'),
        ),
    ]
