# Generated by Django 2.0.5 on 2018-08-11 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0027_auto_20180811_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='grade',
            field=models.CharField(choices=[('O', 'O'), ('A+', 'A+'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('C+', 'C+'), ('C', 'C'), ('P', 'P'), ('F', 'F'), ('FE', 'FE')], max_length=2),
        ),
    ]
